// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD48RHSth-yWNlTPycSDW94L1rPABKC_Ss',
    appId: '1:345206435550:web:e9d52c5c41119052fb1c4f',
    messagingSenderId: '345206435550',
    projectId: 'catalogo-peliculas-firebase',
    authDomain: 'catalogo-peliculas-firebase.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-firebase.firebasestorage.app',
    measurementId: 'G-DL8S0ZV3QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD68PUfHRXv8-XYMLdiR3YJilOzE4JRqvY',
    appId: '1:345206435550:android:c19bd1001959668cfb1c4f',
    messagingSenderId: '345206435550',
    projectId: 'catalogo-peliculas-firebase',
    storageBucket: 'catalogo-peliculas-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATHb8AqfESZqpZEdjYMxswRCGnGm8N6Z0',
    appId: '1:345206435550:ios:45c6528b4d6a909afb1c4f',
    messagingSenderId: '345206435550',
    projectId: 'catalogo-peliculas-firebase',
    storageBucket: 'catalogo-peliculas-firebase.firebasestorage.app',
    iosBundleId: 'com.example.ldsw34Widgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATHb8AqfESZqpZEdjYMxswRCGnGm8N6Z0',
    appId: '1:345206435550:ios:45c6528b4d6a909afb1c4f',
    messagingSenderId: '345206435550',
    projectId: 'catalogo-peliculas-firebase',
    storageBucket: 'catalogo-peliculas-firebase.firebasestorage.app',
    iosBundleId: 'com.example.ldsw34Widgets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD48RHSth-yWNlTPycSDW94L1rPABKC_Ss',
    appId: '1:345206435550:web:868425a201eb217bfb1c4f',
    messagingSenderId: '345206435550',
    projectId: 'catalogo-peliculas-firebase',
    authDomain: 'catalogo-peliculas-firebase.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-firebase.firebasestorage.app',
    measurementId: 'G-8JPJ82FE2F',
  );
}
